version: '3'

services:
  db:
    image: postgis/postgis:13-3.0-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgres
  server:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - 3333:3000

volumes:
  postgres:
