version: '3'

services:
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  redis-ui:
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  db:
    image: postgis/postgis:13-3.0-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgres/data/pgdata
    volumes:
      - postgres:/var/lib/postgres/data
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  backend:
    build:
      context: .
      dockerfile: ./.docker/go/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        GO_VERSION: ${GO_VERSION:-1.21}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      frontend:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./:/app
      - go_pkg:/go
    healthcheck:
      test: curl -f http://localhost:${PORT:-3000}/healthz
      interval: 5s
    ports:
      - ${PORT:-3000}:3000

  frontend:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        NODEJS_VERSION: ${NODEJS_VERSION:-18.12}
    volumes:
      - ./:/app
    healthcheck:
      test: test -f /app/build/index.html
      interval: 5s

volumes:
  redis:
  postgres:
  go_pkg:
