version: '3'

services:
  db:
    image: postgis/postgis:13-3.0-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgres
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  server:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        GO_VERSION: ${GO_VERSION:-1.21}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
      - go_pkg:/go
    ports:
      - ${PORT:-3000}:${PORT:-3000}

volumes:
  postgres:
  go_pkg:
