version: '3'

services:
  production:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        GO_VERSION: ${GO_VERSION:-1.21}
        NODEJS_VERSION: ${NODEJS_VERSION:-18.12}
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    healthcheck:
      test: curl -f http://localhost:${PORT:-3000}/healthz
      interval: 5s
    ports:
      - 3333:3000
